vp:
  image: rikmoedt/fabric-peer:0.5-dp 
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_PRIVACY=true
  command: sh -c "sleep 5; peer node start"
